package com.angelis.tera.game.models.dialog.enums;

public enum DialogIconEnum {
    DEFAULT(1),

    DEFAULT_QUEST(4),

    GUILD_QUEST_REWARD(8),
    MISSION_QUEST_REWARD(9),
    NORMAL_QUEST_REWARD(10),
    UNK_QUEST_REWARD(11),

    GUILD_QUEST_PROGRESS(12),
    REPEATED_GUILD_QUEST_PROGRESS(13),
    MISSION_QUEST_PROGRESS(14),
    REPEATED_MISSION_QUEST_PROGRESS(15),
    NORMAL_QUEST_PROGRESS(16),
    REPEATED_NORMAL_QUEST_PROGRESS(17),
    UNK_QUEST_PROGRESS(18),
    REPEATED_UNK_QUEST_PROGRESS(19),

    GUILD_QUEST_START(20),
    REPEATED_GUILD_QUEST_START(21),
    MISSION_QUEST_START(22),
    REPEATED_MISSION_QUEST_START(23),
    NORMAL_QUEST_START(24),
    REPEATED_NORMAL_QUEST_START(26),
    UNK_QUEST_START(27),
    REPEATED_UNK_QUEST_START(28),

    CENTERED(31),
    CENTERED_GRAY(36); // OK
    
    public final int value;
    
    DialogIconEnum(int value) {
        this.value = value;
    }
}
